name: Price Monitor

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: write  # Need this to commit price history

jobs:
  check_price:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Get all history for all branches
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Initialize or fetch price history
      run: |
        # Configure git
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Try to create price-history branch if it doesn't exist
        if ! git ls-remote --heads origin price-history; then
          git checkout --orphan price-history
          git rm -rf .
          git commit --allow-empty -m "Initialize price-history branch"
          git push origin price-history
          git checkout main
        else
          git fetch origin price-history
          git checkout price-history -- price_history_*.json || true
          git checkout main
        fi
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run price monitor
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        PRODUCT_URL_1: ${{ secrets.PRODUCT_URL_1 }}
        PRODUCT_URL_2: ${{ secrets.PRODUCT_URL_2 }}
      run: python monitor_example.py
    
    - name: Store price history
      if: success()
      run: |
        # Switch to price-history branch
        git fetch origin price-history
        git checkout price-history
        
        # Copy JSON files from working directory
        cp -f ../price_history_*.json . || true
        
        # Commit and push changes
        git add price_history_*.json
        git commit -m "Update price history [skip ci]" || echo "No changes to commit"
        git push origin price-history 