name: Price Monitor

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: write  # Need this to commit price history

jobs:
  check_price:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1  # Get the latest commit
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run price monitor
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        PRODUCT_URL_1: ${{ secrets.PRODUCT_URL_1 }}
        PRODUCT_URL_2: ${{ secrets.PRODUCT_URL_2 }}
        # Add more product URLs as needed
      run: python monitor_example.py
    
    - name: Store price history
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: price-history
        path: price_history_*.json
        retention-days: 90  # Keep history for 90 days 