name: Price Monitor

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: write  # Need this to commit price history

jobs:
  check_price:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Get all history for all branches
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Initialize or fetch price history
      run: |
        # Configure git
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        echo "Current directory contents before:"
        ls -la
        
        # Create and switch to a new price-history branch
        git checkout --orphan price-history || true
        git rm -rf . || true
        git commit --allow-empty -m "Initialize price-history branch" || true
        git push origin price-history || true
        
        # Return to main branch
        git checkout main
        
        echo "Current directory contents after:"
        ls -la
        echo "Looking for price history files:"
        find . -name "price_history_*.json"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run price monitor
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        PRODUCT_URL_1: ${{ secrets.PRODUCT_URL_1 }}
        PRODUCT_URL_2: ${{ secrets.PRODUCT_URL_2 }}
      run: python monitor_example.py
    
    - name: Store price history
      if: success()
      run: |
        echo "Files before switching branch:"
        ls -la
        
        # Switch to price-history branch
        git checkout price-history
        
        echo "Files after switching branch:"
        ls -la
        
        # Copy JSON files from working directory
        cp -f price_history_*.json . || true
        
        echo "Files after copying:"
        ls -la
        
        # Commit and push changes
        git add price_history_*.json || true
        git status
        git commit -m "Update price history [skip ci]" || echo "No changes to commit"
        git push origin price-history || true 